# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "de"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Lennard Meyers - Links"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "@lennard.my"

# Tagline section text
tagline: >-
    Ich bin Lenny, ein DJ aus Hamburg. Für eine Buchung oder Kooperationen, schreibt mir gerne eine E-Mail an (lennard.my@outlook.de).

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-envelope"
      text: "Email"
      url: "mailto: lennard.my@outlook.de"
      title: "Email: lennard.my@outlook.de"
      alt: "lennard.my@outlook.de"
      target: "_blank"
  - link:
      icon: "fa-brands fa-tiktok"
      text: "TikTok"
      url: "https://www.tiktok.com/@lennard.my"
      title: "Tiktok"
      alt: "Lennard's Instagram"
      target: "_blank"
  - link:
      icon: "fa-brands fa-instagram"
      text: "Instagram"
      url: "https://www.instagram.com/lennard.my/"
      title: "Instagram"
      alt: "Lennard's Instagram"
      target: "_blank"

# Footer text
footer: >
    Hey, folgt mir gerne Instagram oder Tiktok!

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://link.zhgchg.li" target="_blank">ZhgChgLi</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
